// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnujTJhb8Zy6rT_vrFhb42c-dwFsaC7jk',
    appId: '1:525020967173:web:77da312a878bd7127ec76c',
    messagingSenderId: '525020967173',
    projectId: 'meubares',
    authDomain: 'meubares.firebaseapp.com',
    storageBucket: 'meubares.firebasestorage.app',
    measurementId: 'G-GEESM9DR6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW4G5BiUaj3m668lWJ1fan8fIdRpuy0Yc',
    appId: '1:525020967173:android:1de0acaa1b48ab867ec76c',
    messagingSenderId: '525020967173',
    projectId: 'meubares',
    storageBucket: 'meubares.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4412jNFjEqkayzW16Srgf34o7BWdJsXs',
    appId: '1:525020967173:ios:88a45d625be6abcc7ec76c',
    messagingSenderId: '525020967173',
    projectId: 'meubares',
    storageBucket: 'meubares.firebasestorage.app',
    iosBundleId: 'com.example.meubar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4412jNFjEqkayzW16Srgf34o7BWdJsXs',
    appId: '1:525020967173:ios:88a45d625be6abcc7ec76c',
    messagingSenderId: '525020967173',
    projectId: 'meubares',
    storageBucket: 'meubares.firebasestorage.app',
    iosBundleId: 'com.example.meubar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnujTJhb8Zy6rT_vrFhb42c-dwFsaC7jk',
    appId: '1:525020967173:web:17e54ac4fe7187437ec76c',
    messagingSenderId: '525020967173',
    projectId: 'meubares',
    authDomain: 'meubares.firebaseapp.com',
    storageBucket: 'meubares.firebasestorage.app',
    measurementId: 'G-KVVSRNG26L',
  );
}
